### ISSUE TITLE
Please stop copying my code

### ISSUE THREAD

**Issue by cmfcmf** [lelouch77/docusaurus-lunr-search#12]
Hi @lelouch77,

I noticed that you copied (commit https://github.com/lelouch77/docusaurus-lunr-search/commit/9f7a0c96d346a19af786f6eaca09fec7dd79dfd2) almost the entire multi language search implementation from [my library](https://github.com/cmfcmf/docusaurus-search-local) without any attribution or compliance with the license of my code. Please remove the offending code from your library or comply with the license.

Here's a list of code you copied from me:

| My original code | Copied code in your repo |
| ---------------- | ------------------------ |
| https://github.com/cmfcmf/docusaurus-search-local/blob/41d577cb736344faea94347b364f74c4398ea8ec/src/index.js#L46-L71 | https://github.com/lelouch77/docusaurus-lunr-search/blob/7baaafc12573eb39c6daa6b99b64f30ecc8f195c/src/utils.js#L5-L33
| https://github.com/cmfcmf/docusaurus-search-local/blob/41d577cb736344faea94347b364f74c4398ea8ec/src/index.js#L145-L150 | https://github.com/lelouch77/docusaurus-lunr-search/blob/7baaafc12573eb39c6daa6b99b64f30ecc8f195c/src/utils.js#L35-L42
| Looks like you forgot to add the generated file to the .gitignore file: https://github.com/cmfcmf/docusaurus-search-local/blob/41d577cb736344faea94347b364f74c4398ea8ec/.gitignore#L1 | https://github.com/lelouch77/docusaurus-lunr-search/blob/7baaafc12573eb39c6daa6b99b64f30ecc8f195c/src/lunr.client.js#L1-L5

---

It was a lot of work to understand and get multilingual search working. 
Seeing you just copying all of that makes me sad and wonder what you'll copy next. :confused:

**Comment by lelouch77** [comment]
Hi @cmfcmf, Since your code was licensed under MIT, I thought I can use it. I am sorry if it's offended you, I mentioned you in README file, if you are still not happy with it, I will remove it.

Once again sorry 🙏

**Comment by cmfcmf** [comment]
Thank you for apologizing and understanding my situation. I was offended when I stumbled upon my code in your repository, but your comment made me realise that there was likely no ill intention on your part.

Thank you for adding that sentence to the README. To be clear, the title of this issue should have been "Please stop copying my code *without attribution*" (sorry for the confusion). Because you're exactly right, my code is under the MIT license and thus explicitly allows copying the code. However, the MIT license requires you to include the copyright notice of the original code if you copy code. Therefore I would appreciate if you could also include a short comment similar to [this comment](https://github.com/cmfcmf/docusaurus-search-local/blob/3fe103f4f11abcc218a225a87e310449c4a7b840/src/theme/SearchBar/index.js#L1-L4) in https://github.com/lelouch77/docusaurus-lunr-search/blob/master/src/utils.js.

**Comment by lelouch77** [comment]
Yep I added it https://github.com/lelouch77/docusaurus-lunr-search/blob/master/src/utils.js

Thanks and sorry for the misunderstanding.

Always add attribution lesson learned :+1:

**Comment by cmfcmf** [comment]
Thank you!
