### ISSUE TITLE
Docs only mode root docs not indexed

### ISSUE THREAD

**Issue by KohheePeace** [lelouch77/docusaurus-lunr-search#17]
Hi @lelouch77 , really thanks for this awesome repogitory.

I found that If I'm using this repo with docs only mode of docusaurus, the root docs is not indexed.

Thanks.

**Comment by lelouch77** [comment]
Hi @KohheePeace , Thanks for reporting the issue.
Base URL will not be indexed by default, I have added an option for it in the new version(`2.1.6`), try setting it
```
    plugins: [[ require.resolve('docusaurus-lunr-search'), {
      indexBaseUrl: true
    }]
```
https://github.com/lelouch77/docusaurus-lunr-search#indexbaseurl

And thanks for your  `docusaurus-pdf` plugin, it awesome :)

**Comment by KohheePeace** [comment]
yay🎉 thanks for quick fixing👍
