### ISSUE TITLE
Incompatible with node version < 12

### ISSUE THREAD

**Issue by ZachJW34** [lelouch77/docusaurus-lunr-search#18]
Docusaurus supports [Node.js version >= 10.15.1](https://v2.docusaurus.io/docs/installation/#requirements), but this package only supports Node.js version >= 12 after adding [worker_threads](https://github.com/lelouch77/docusaurus-lunr-search/commit/2369254da8ac15c2b8b8f7d095d2b20893fba65f), a Node.js 12 API. This should be clearly noted in the README.md.

**Comment by ZachJW34** [comment]
I see the updated README. Thanks @lelouch77!

**Comment by lelouch77** [comment]
Thanks for reporting it @ZachJW34 :slightly_smiling_face:
