### ISSUE TITLE
Is it typo tolerant?

### ISSUE THREAD

**Issue by elgalu** [lelouch77/docusaurus-lunr-search#19]

**Comment by lelouch77** [comment]
I don't get it ... Can you explain it a bit ..

**Comment by elgalu** [comment]
Does the full text search solution tolerates typos and misspelling. I tried
and it doesn't. Algolia handles this properly

**Comment by lelouch77** [comment]
Ya, the underlying search engine is lunr.js which is not typo tolerant ...
