### ISSUE TITLE
[ja] TypeError: lunr.TinySegmenter is not a constructor

### ISSUE THREAD

**Issue by onoh** [lelouch77/docusaurus-lunr-search#47]
i have a same problem with https://github.com/cmfcmf/docusaurus-search-local/issues/12 for lang "ja"

```
TypeError: lunr.TinySegmenter is not a constructor
    at ${dir}/node_modules/lunr-languages/lunr.ja.js:86:21
```

when i put the code below to `node_modules/lunr-languages/lunr.ja.js`, build was successful.
```
require('./tinyseg.js')(lunr) // + add
var segmenter = new lunr.TinySegmenter() // インスタンス生成
```

thanks

**Comment by lelouch77** [comment]
New version `2.1.12` is published

**Comment by onoh** [comment]
thx a lot!!
