### ISSUE TITLE
Multiple chunks emit assets to the same filename server.bundle.js

### ISSUE THREAD

**Issue by Chris-ganta** [lelouch77/docusaurus-lunr-search#53]
Shows with the following error messages after:` npm run build`

node_modules/webpack/lib/Compilation.js:3864:12
node_modules/webpack/lib/Cache.js:85:6
node_modules/webpack/lib/Cache.js:39:11
node_modules/webpack/lib/cache/IdleFileCachePlugin.js:66:9
node_modules/webpack/lib/Cache.js:88:6
node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error building locale=en

Request for help, Please

**Comment by slorber** [comment]
Duplicate of https://github.com/lelouch77/docusaurus-lunr-search/issues/52
