### ISSUE TITLE
Search field never initializes

### ISSUE THREAD

**Issue by mac-outlier** [lelouch77/docusaurus-lunr-search#73]
Even when running in production mode, the search field never gets enabled and removes "Loading...". I see in `SearchBar/index.js` that it depends on `indexReady` getting toggled. What mechanism affects that? My docusaurus instance is behind a login, so Algolia won't be able to crawl it. I've been under the impression that this component doesn't depend on Algolia and will simply index it locally via lunr.js. Is this correct?

**Comment by alanwguo** [comment]
I ran into this issue as well. It seems to be related to backwards-incompatible changes to docusaurus v2.

I opened a PR here with the changes I needed to do to fix this for me: https://github.com/lelouch77/docusaurus-lunr-search/pull/74

or feel free to use my fork: https://github.com/alanwguo/docusaurus-lunr-search

**Comment by mac-outlier** [comment]
Thanks for the help. I tried your PR but it didn't address my situation. In my case, I had `.md` files in the `docs` folder and they weren't getting indexed at all, since this plugin expects html. I had to go with a different plugin.
